### ISSUE TITLE
Rerunning a migration still inserts records into the migration collection

### ISSUE THREAD

**Issue by jasiedu** [flashstockinc/mongoose-data-migrate#2]
Every time I run the following migration, a record gets inserted into the migration database.
I was under the impression that this would be a no-op if you run it more than once.
Is that not the case?

exports.up = function (next) {
    console.log('    --> This is migration 2015-12-13-2246.js being applied');
    next();
};

exports.down = function (next) {
    console.log('    --> This is migration 2015-12-13-2246.js being rollbacked');
    next();
};

**Comment by naelshawwa** [comment]
The record that's inserted is just an audit trail of when the tool executed. The actual migrations applied (up or down) are stored within the "migrations" array within document. 

You will see that the records that are inserted in your example contain an empty.
