### ISSUE TITLE
Is this project still alive

### ISSUE THREAD

**Issue by tommarien** [flashstockinc/mongoose-data-migrate#5]
Hi 

We are using this beautiful project but have some issues with it, is it still alive, do you need any help maintaining ?

Kind regards

Tom

**Comment by brianviveiros** [comment]
Hi Tom,

Apologies for the late reply.  This project was created by myself and another developer but we have since moved on to other roles and other technology stacks.  I'll reach out to the current team at FlashStock and see if they wish to maintain it or perhaps find a new owner.

Brian

**Comment by tommarien** [comment]
Thanks for the update

Keep me in the loop

Kind regards

Tom

**Comment by naelshawwa** [comment]
Hi Tom, 

Nael from Flashstock here. I wasn't aware of this repository, but we still use this project at work and will be maintaining it. 

Please bear with me while I sort out the ownership of the repo with Github. 

I'll keep you posted

**Comment by tommarien** [comment]
@naelshawwa Any update on status ;)

**Comment by naelshawwa** [comment]
sorry @tommarien: still waiting on transferring the ownership of this repo. Hopefully soon...

**Comment by naelshawwa** [comment]
It's live now : )
